[package]
name = "Rusql"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
dirs = "6.0.0"
mysql = "25.0.1"
prettytable = "0.10.0"
rustyline = "15.0.0"
structopt = "0.3.26"
term_size = "0.3.2"
